export const offerConstants = {
    CREATE_OFFER_SUCCESS: 'CREATE_OFFER_SUCCESS',
    CREATE_OFFER_ERROR: 'CREATE_OFFER_ERROR',
    CREATE_OFFER_REQUEST: 'CREATE_OFFER_REQUEST',

    DELETE_SUCCESS: 'DELETE_OFFER_SUCCESS',
    DELETE_ERROR: 'DELETE_OFFER_ERROR',
    DELETE_REQUEST: 'DELETE_OFFER_REQUESTED',

};