export const USER_STATUS_CHANGE = 'USER_STATUS_CHANGE';
export const USER_UPDATE = 'USER_UPDATE';

export const USER_TYPING = 'USER_TYPING';
export const MESSAGE_CREATED = 'MESSAGE_CREATED';
export const MESSAGE_READ = 'MESSAGE_READ';